apiVersion: v1
kind: Service
metadata:
  name: prestodb-service
  labels:
    app: prestodb-service
spec:
  type: NodePort
  ports:
  - name: prestodb-app
    port: 80
    nodePort: 30001
    targetPort: 8080
  selector:
    app: coordinator
