apiVersion: v1
kind: Service
metadata:
  name: prestodb-objectstorage-service
  labels:
    app: prestodb-objectstorage-service
spec:
  type: NodePort
  ports:
  - name: storage-app
    port: 80
    nodePort: 6443
    targetPort: 8080
  selector:
    app: prestodb-objectstorage-service
